name: my first workflow
on: push 

jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
        - name: weclome message
          uses: echo "my first github actions file"

        - name: list of files
          uses: ls 
        
        - name: readfile
          uses: cat README.md

          
    